server:
  port: ${SERVER_PORT:8080}


spring:
  profiles:
    active: default
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}
      database: ${MONGODB_DATABASE:employee}

