server:
  port: ${SERVER_PORT:8080}


spring:
  config:
    activate:
      on-profile: deploy
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}
      database: ${MONGODB_DATABASE:employee}
      username: ${MONGODB_USERNAME}
      password: ${MONGODB_PASSWORD}

