server:
  port: ${SERVER_PORT:8080}


spring:
  config:
    activate:
      on-profile: deploy
  data:
    mongodb:
      uri: mongodb+srv://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@${MONGODB_HOST:localhost}/${MONGODB_DATABASE:employee}